name: Run grit patterns test

env:
  GRIT_TELEMETRY_DISABLED: "true"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [nscloud-ubuntu-22.04-amd64-4x16]
        node-version: [20.x]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install-ruff
        run: |
          pip install ruff

      - name: Install @getgrit/launcher
        run: npm install -g @getgrit/launcher

      - name: Run doctor
        run: npx grit doctor

      - name: Run grit patterns test
        run: npx grit patterns test
